#-------------------------------
# General Site Settings

title: Angela Wang
description: Translator and Chinese social media strategist and editor
email: angeler.wang@hotmail.com

menu:
- {name: 'Projects', url: ''}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Translator and Chinese social media strategist and editor'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  Hi! I'm Angela Wang, a native Chinese speaker from Shandong, China. I'm a keen translator and have several years of experience in the realm of Chinese social media (Sina Weibo, Wechat, Douban); creating campaigns, designing strategies and curating content.
  I'm available for freelance project, feel free to contact me [by email](mailto:angeler.wang@hotmail.com).

  You may see my full resume [here](https://angelerwang.github.io/CV/).

contact: >
  # Contact

  You may contact me [by email](mailto:angeler.wang@hotmail.com) for any inquiry regarding translation from English to Chinese of Social Media Marketing in China.

#-------------------------------
# Work Section

projects:
- {name: 'Star Alliance', folder: 'proj-1', file: 'projects/star-alliance.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
